[package]
name = "cosmwasm-event-derive"
version = "0.16.2"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0.32"
convert_case = "0.4.0"

[dev-dependencies]
cosmwasm-std = { path = "../std", version = "0.16.2" }
