[package]
name = "cosmwasm-storage"
version = "0.14.0-0.4.0"
authors = ["LINE Plus Corporation"]
edition = "2018"
description = "CosmWasm library with useful helpers for Storage patterns"
repository = "https://github.com/line/cosmwasm/tree/main/packages/storage"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["iterator"]
# This enables iterator functionality, as exposed in cosmwasm-std/iterator
iterator = ["cosmwasm-std/iterator"]

[dependencies]
# Uses the path when built locally; uses the given version from crates.io when published
cosmwasm-std = { path = "../std", version = "0.14.0-0.4.0", default-features = false }
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }
