# As we use Squash `Squash and merge` for the PR merging rule, the PR title validation only needed.
titleOnly: true

# The type rule is based on the Angular convention
# > https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type
types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
  - release
