[package]
name = "cosmwasm-check"
version = "1.1.9+0.8.1"
authors = ["Mauro Lacy <mauro@lacy.com.es>"]
edition = "2021"
description = "A CLI tool for verifying CosmWasm smart contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/check"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0.57"
clap = "4"
colored = "2"
cosmwasm-vm = { path = "../vm", version = "1.1.9+0.8.1" }
cosmwasm-std = { path = "../std", version = "1.1.9+0.8.1" }

[dev-dependencies]
assert_cmd = "=2.0.10" # 2.0.11+ requires Rust 1.65.0 which we currently don't want to make the minimum if possible
predicates = "3"
