name: changelog

on:
  pull_request:

jobs:
  changelog:
    name: Generate Changelog
    if: startsWith(github.event.pull_request.head.ref, 'release-v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get version
        id: get_version
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: echo ::set-output name=VERSION::${HEAD_REF#release-v}
      - name: Create new tag
        run: |
          git tag v${{ steps.get_version.outputs.VERSION }}

      - name: Update CHANGELOG-LINK.md
        working-directory: ./
        run: |
          docker pull quay.io/git-chglog/git-chglog:latest
          docker run -v "$PWD":/workdir quay.io/git-chglog/git-chglog -o CHANGELOG-LINK.md v0.12.0-0.1.0..
      - name: Merge CHANGELOG-LINK.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Update CHANGELOG-LINK.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
