name: Contract Development

# Pushes to long living branches and all PRs
on:
  push:
    branches:
      - main
      - 0.[0-9]+
  pull_request:

env:
  RUST_BACKTRACE: 1

jobs:
  test-hackatom:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: macOS
            os: macOS-latest
          - build: Windows
            os: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./contracts/hackatom
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.51.0
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Build hackatom wasm
        run: cargo wasm --locked
      - name: Unit Test hackatom
        run: cargo unit-test --locked
      - name: Integration Test hackatom
        run: cargo integration-test --locked
