name: Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    container: cibuilds/github:0.13
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install libgcc
        run: apk add libgcc
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.57.0
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Get version
        id: get_version
        run: |
            VERSION=$(./devtools/get_version.sh)
            echo ::set-output name=version::$VERSION
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
      - name: Check version
        id: tag_check
        uses: dudo/tag_check@v1.1.1
        with:
          version: ${{ steps.get_version.outputs.version }}
          git_tag_prefix: v
      - name: Create new tag
        run: |
          if [ -z "${{ steps.get_version.outputs.version }}" ]; then
              git tag ${{ steps.get_version.outputs.version }}
          fi
      - name: Install Docker client
        run: |
          apk add docker-cli
      - name: Prepare volume with source code
        run: |
          # create a dummy container which will hold a volume with config
          docker create -v /code --name with_code alpine /bin/true
          # copy a config file into this volume
          docker cp ./Cargo.toml with_code:/code
          docker cp ./contracts with_code:/code
          docker cp ./packages with_code:/code
      - name: Build development contracts
        run: |
          echo "Building all contracts under ./contracts"
          docker run --volumes-from with_code cosmwasm/rust-optimizer:0.12.1 ./contracts/*/
      - name: Check development contracts
        working-directory: ./
        run: |
          echo "Checking all contracts under ./artifacts"
          docker run --volumes-from with_code rust:1.54.0 /bin/bash -e -c 'cd ./code/packages/vm; ./examples/check_contract.sh ../../artifacts/*.wasm'
          docker cp with_code:/code/artifacts .

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          body: ${{ github.event.pull_request.body }}
          files: |
            ./artifacts/*
          draft: false
          prerelease: false
