name: Release

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release-v')
    runs-on: ubuntu-latest
    container: cibuilds/github:0.13
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${HEAD_REF#release-v}
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
      - name: Install Docker client
        run: |
          apk add docker-cli
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare volume with source code
        run: |
          # create a dummy container which will hold a volume with config
          docker create -v /code --name with_code alpine /bin/true
          # copy a config file into this volume
          docker cp ./Cargo.toml with_code:/code
          docker cp ./contracts with_code:/code
          docker cp ./packages with_code:/code
      - name: Build development contracts
        run: |
          echo "Building all contracts under ./contracts"
          docker run --volumes-from with_code cosmwasm/rust-optimizer:0.11.0 ./contracts/*/
      - name: Check development contracts
        working-directory: ./
        run: |
          echo "Checking all contracts under ./artifacts"
          docker run --volumes-from with_code rust:1.51.0 /bin/bash -e -c 'cd ./code/packages/vm; ./examples/check_contract.sh ../../artifacts/*.wasm'
          docker cp with_code:/code/artifacts .
          ls -la

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          body: ${{ github.event.pull_request.body }}
          files: |
            ./artifacts/*
          draft: false
          prerelease: false
