name: Tests

on:
  push:
    branches:
      - main
      - 0.[0-9]+
  pull_request:

jpbs:
  package_crypto:
    name: package_crypto
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.50.0
          target: wasm32-unknown-unknown
          profile: minimal
          override: true
      - name: Cache cargo
        uses: actions/cache@v2
        with:
          path: ~/.cargo
          key: cargocache-v2-package_crypto-rust:1.50.0-{{ checksum "Cargo.lock" }}
      - name: Version information
        run: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - name: Build
        working_directory: ~/project/packages/crypto
        run: cargo build --locked
      - name: Run tests
        working_directory: ~/project/packages/crypto
        run: cargo test --locked
